# Generated by Django 4.0.3 on 2022-07-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_bursary_bursary_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursary',
            name='bursary_field_study_2',
        ),
        migrations.RemoveField(
            model_name='bursary',
            name='bursary_field_study_3',
        ),
        migrations.AlterField(
            model_name='bursary',
            name='bursary_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
