# Generated by Django 4.0.3 on 2022-07-23 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_remove_bursary_bursary_field_study_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('school_name', models.CharField(max_length=100)),
                ('school_undergraduate_program', models.FileField(upload_to='pdf/undergraduate')),
                ('school_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_requirements', models.TextField(blank=True, null=True)),
                ('course_min_aps', models.IntegerField()),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.school')),
            ],
        ),
    ]
