# Generated by Django 4.0.3 on 2022-07-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_faculty_email_school_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='closing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=100),
        ),
    ]
