# Generated by Django 4.0.3 on 2022-07-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_institution_closing_institution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='bursary_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='bursary_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_undergraduate_program',
            field=models.FileField(blank=True, null=True, upload_to='pdf/undergraduate'),
        ),
    ]
