# Generated by Django 4.0.3 on 2022-07-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_bursary_bursary_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
